name: CI & Deploy Smart Farming App

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit smoke test
      run: |
        nohup streamlit run app.py --server.headless true --server.port 8501 &
        sleep 15
        curl -I http://localhost:8501

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/smart-farming-ai:latest

  deploy-to-cloud:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Railway or Render
      run: echo "Deployment step — configure your platform (Railway/Render) webhook here"
